### ISSUE TITLE
Unsubscribe example calls MQTT_Subscribe

### ISSUE THREAD

**Issue by boraozgen** [FreeRTOS/coreMQTT#119]
Hi all,

found a typo:

https://github.com/FreeRTOS/coreMQTT/blob/4b8674a80627e8a210a38e6fa2f5fc2731ede0e5/source/include/core_mqtt.h#L563

Cheers

**Comment by yourslab** [comment]
Thank you for catching this typo. We will update the comment appropriately.

**Comment by yourslab** [comment]
Thanks again and feel free to point out any other issues you see. A PR to fix this typo has been merged, so this issue can be closed.
