### ISSUE TITLE
MQTT Subscribing for published data (Payload)

### ISSUE THREAD

**Issue by Abhi2109** [FreeRTOS/coreMQTT#162]
Hi,
I have a query , after using the AWS library can i get the data which i have sent to AWS IOT core using MQTT?

Lets say i sent {"Temp":80} now as soon as sent the data , i want to receive once it got published using MQTT.

**Comment by mukesh-2538** [comment]
Yes, you can subscribe to the same topic and receive it. please refer this sample code
[https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/mqtt/mqtt_demo_basic_tls/mqtt_demo_basic_tls.c](url)

**Comment by Abhi2109** [comment]
The link is not opening for me

**Comment by paulbartell** [comment]
@Abhi2109 Please try this again: https://github.com/aws/aws-iot-device-sdk-embedded-C/blob/main/demos/mqtt/mqtt_demo_basic_tls/mqtt_demo_basic_tls.c

**Comment by sukhmanm** [comment]
Hi @Abhi2109,

I will go ahead and close this issue as it appears there are no recent updates. Please feel free to open a new issue if you have any further questions on this topic. Thank you.
