### ISSUE TITLE
Assert fails on empty string

### ISSUE THREAD

**Issue by dimmykar** [FreeRTOS/coreMQTT#251]
I'm trying to port my code from `v1.2.0` to `v2.1.0`, which is integrated into the coreMQTT-Agent. However, I have come across an unexpected assertion firing which was not present in previous `v1.2.0`. Upon analyzing the code, I discovered that the problem also exists in `v2.1.1` too.

https://github.com/FreeRTOS/coreMQTT/blob/b0acf49c6c3a72d5ed7cbc4b617f2243809dc42d/source/core_mqtt.c#L1869

In my code I am trying to connect to a test broker that does not require a login and password. That's why I pass empty strings as `""` and not `NULL`. `strlen` of the empty string returns `0`, so this assertion fires: I have a valid string that is not `NULL`, but its length is `0`.

Workaround of this problem can be achieved by passing a pointer to `NULL` instead of the empty string `""`. But still I think this case should not be handled as fatal error.

**Comment by archigup** [comment]
Thanks for the bug report! I'll open a PR to fix this shortly.
