### ISSUE TITLE
MQTT_Status_strerror() desn't implement the MQTTNeedMoreBytes enum value.

### ISSUE THREAD

**Issue by slapab** [FreeRTOS/coreMQTT#254]
**Bug description:** 
`MQTT_Status_strerror()` for the `MQTTNeedMoreBytes` status returns `"Invalid MQTT Status code"` string. 

---

**Expectations:** 
`MQTT_Status_strerror()` for the `MQTTNeedMoreBytes` status should return `"MQTTNeedMoreBytes"` string.

**Comment by AniruddhaKanhere** [comment]
Hello @slapab,

Thank you for catching and reporting this bug. We are working on a fix and it should be out soon.

Thank you,
Aniruddha

**Comment by AniruddhaKanhere** [comment]
Hello @slapab as the above mentioned PR was merged, I shall be closing this issue.

If you feel that your issue isn't resolved, feel free to reopen this issue or create a new one.

Thanks,
Aniruddha
