### ISSUE TITLE
Roadmap to support MQTT 5.0?

### ISSUE THREAD

**Issue by overheat** [FreeRTOS/coreMQTT#265]

**Comment by bradleysmith23** [comment]
Hello, thank you for the inquiry! We prefer to discuss these things in the [FreeRTOS Forums](https://forums.freertos.org/). By doing this it helps users navigate Github tickets for feature requests, bug reports, etc. without filtering through other conversations. So, please repost your question to the [FreeRTOS Forums](https://forums.freertos.org/) - you can use your github account to sign in. Thank you!
