### ISSUE TITLE
 undefined reference to `main' in building phase

### ISSUE THREAD

**Issue by raphael10-collab** [FreeRTOS/coreMQTT#272]
When building coreMQTT in Ubuntu 23.10 I get this error:

    raphy@raohy:~/libpeer/dependencies/coreMQTT$ gcc -I source/include/ -DMQTT_DO_NOT_USE_CUSTOM_CONFIG -I source/interface/ source/core_mqtt.c source/core_mqtt_state.c source/core_mqtt_serializer.c -o coreMQTT
    /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/13/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
    (.text+0x1b): undefined reference to `main'
    collect2: error: ld returned 1 exit status

What am I doing wrong? How make it work?

**Comment by aggarg** [comment]
You are trying to compile a library. The library is supposed to be used in an application and that is why it does not supply main. 

You can look at these samples for learning how to use this library in an application - https://github.com/FreeRTOS/FreeRTOS/tree/main/FreeRTOS-Plus/Demo/coreMQTT_Windows_Simulator.

We want to keep all the discussions in one place and therefore, I'd request you to please open a forum issue if you have more questions - https://forums.freertos.org/.
