### ISSUE TITLE
Compile error for comparison of integer expressions of different signedness

### ISSUE THREAD

**Issue by skyfishyubo** [FreeRTOS/coreMQTT#282]
../../../../lib/mqtt_client/coreMQTT/source/core_mqtt.c: In function 'sendConnectWithoutCopy':

../../../../lib/mqtt_client/coreMQTT/source/core_mqtt.c:2220:50: error: comparison of integer expressions of different signedness: 'int' and 'unsigned int' [-Werror=sign-compare]

         assert( ( pIndex - connectPacketHeader ) <= sizeof( connectPacketHeader ) );

**Comment by moninom1** [comment]
Hello @skyfishyubo  ,
Thank you for bringing this to our attention! We will take a look at this issue. Thank you for your patience!

**Comment by tony-josi-aws** [comment]
@skyfishyubo 
Closing this issue as #283 should fix this. Please feel free to reopen if you think otherwise.
